In [1]:
import numpy as np

# 1. 배열 생성
- 배열이란 순서가 있는 같은 종류의 데이터가 저장된 집합
- numpy 배열을 생성할 때 받는 시퀀스 데이터로 리트스와 튜플 타입의 데이터를 모두 사용할 수 있지만 주로 **리스트 데이터**를 이용한다.

In [3]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1, a1.dtype

(array([0, 1, 2, 3, 4, 5]), dtype('int32'))

In [4]:
data2 = [0, 1.1, 2, 3, 4, 5.1]
a2 = np.array(data2)
a2, a2.dtype

(array([0. , 1.1, 2. , 3. , 4. , 5.1]), dtype('float64'))

In [5]:
np.array([0, 1, 2, 3])

array([0, 1, 2, 3])

In [10]:
data = np.array([[1, 2, 3],
         [4, 5, 6]])
data, data.dtype, data.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 dtype('int32'),
 (2, 3))

In [9]:
data = np.array([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]])
data, data.dtype, data.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'),
 (3, 3))

## 1-1 범위를 지정해 배열 생성
## arange, linspace

In [11]:
np.arange(0, 12, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [16]:
a = np.arange(12).reshape(4, 3)
a, a.shape # 2차원 배열

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 (4, 3))

In [19]:
b = np.arange(4)
print(b)
print(b.shape)  # 1차원 배열

[0 1 2 3]
(4,)


In [21]:
# 1~10까지 5개의 데이터
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
# 1~10까지 10개의 데이터
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
# 0~파이 까지 동일한 간격으로 나눈 20개의 데이터
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

## 1-2 특별한 형태의 배열 생성
## zeros, ones, eye(단위행렬)

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones(4)

array([1., 1., 1., 1.])

In [27]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# 단위행렬 : n x n인 정사각형 행렬에서 주 대각선이 모두 1이고 나머지는 0인 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 1-3 데이터 타입 변환
## astype(int, float, str)

In [90]:
str1 = np.array(['1.56', '2.56', '3.21'])
num1 = str1.astype(float)
print(str1), print(str1.dtype,'\n')
print(num1), print(num1.dtype)

['1.56' '2.56' '3.21']
<U4 

[1.56 2.56 3.21]
float64


(None, None)

## 1-4 난수 배열의 생성
## rand, randint, randn(가우시안 표준 정규 분포에서 난수 배열 생성)

In [47]:
np.random.rand()

0.01562591071107633

In [50]:
np.random.rand(2, 3)

array([[0.94036114, 0.57263648, 0.75479014],
       [0.50305578, 0.42795251, 0.15392854]])

In [59]:
np.random.rand(4, 6, 2)

array([[[0.97929415, 0.67870167],
        [0.856071  , 0.50692267],
        [0.99858076, 0.52565824],
        [0.53646056, 0.24186108],
        [0.82629565, 0.55163729],
        [0.77100556, 0.94782381]],

       [[0.77418215, 0.03467905],
        [0.18153722, 0.27404634],
        [0.74685848, 0.72700435],
        [0.72673925, 0.81660238],
        [0.85732746, 0.40631684],
        [0.92182003, 0.9461048 ]],

       [[0.03506849, 0.47748354],
        [0.31788296, 0.13254747],
        [0.50412678, 0.05756434],
        [0.7803024 , 0.86087181],
        [0.1233814 , 0.29262637],
        [0.56176335, 0.3676497 ]],

       [[0.92974647, 0.20417451],
        [0.05609879, 0.55952888],
        [0.93152653, 0.86944274],
        [0.47390497, 0.87019094],
        [0.18679126, 0.75295633],
        [0.99402898, 0.82859143]]])

In [60]:
np.random.randint(10, size=(3,4))

array([[3, 7, 5, 7],
       [6, 8, 1, 9],
       [8, 0, 4, 9]])

In [62]:
np.random.randint(1, 30)

18

In [63]:
np.random.randn(4)

array([ 0.69269078,  0.52032385,  2.44369488, -2.07936485])

In [65]:
np.random.randn(3, 4)

array([[ 0.3444482 ,  0.63922327,  0.21505654, -1.29804736],
       [-0.37327633, -0.56542212, -0.18677462, -0.29218162],
       [-1.71565623, -0.62546239, -2.03145917,  0.15338798]])

# 2. 배열의 연산 

In [66]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [67]:
# 합
arr3.sum()

10

In [68]:
#평균
arr3.mean()

2.0

In [69]:
# 표준편차
arr3.std()

1.4142135623730951

In [70]:
# 분산
arr3.var()

2.0

In [71]:
# 최솟값
arr3.min()

0

In [72]:
# 최댓값
arr3.max()

4

In [74]:
arr4=np.arange(1, 6)
arr4

array([1, 2, 3, 4, 5])

In [75]:
# 누적 합
arr4.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)

In [76]:
# 누적 곱
arr4.cumprod()

array([  1,   2,   6,  24, 120], dtype=int32)

## 2-1 행렬 연산
### dot 행렬곱
### transpose전치행렬(행과 열을 바꾼 행렬)
### linalg.inv역행렬(axb=1이 되는 행렬)
### linalg.det행렬식

In [89]:
a = np.array([0, 1, 2, 3]).reshape(2,2)
b= np.array([3, 2, 0, 1]).reshape(2,2)
print(a,'\n')
print(b)

[[0 1]
 [2 3]] 

[[3 2]
 [0 1]]


In [93]:
# 곱셈 1
a.dot(b)

array([[0, 1],
       [6, 7]])

In [94]:
# 곱셈 2
np.dot(a, b)

array([[0, 1],
       [6, 7]])

In [105]:
c = np.array([0, 1, 2, 3, 4, 5]).reshape(3,2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [102]:
# 전치 행렬 1
np.transpose(c)

array([[0, 2, 4],
       [1, 3, 5]])

In [103]:
# 전치 행렬 2
c.transpose()

array([[0, 2, 4],
       [1, 3, 5]])

In [107]:
# 역행렬 
np.linalg.inv(a)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [99]:
# 행렬식
np.linalg.det(a)

-2.0

# 3. 배열의 인덱싱과 슬라이싱

## 3-1 인덱싱

## 3-1-1) 1차원 배열

In [112]:
a1= np.arange(0,51,10)
a1

array([ 0, 10, 20, 30, 40, 50])

In [114]:
a1[1]

10

In [116]:
# 기존 원소 변경
a1[1]= 70
a1

array([ 0, 70, 20, 30, 40, 50])

In [118]:
# 여러개의 원소 선택
a1[[0, 1, 2, 3]]

array([ 0, 70, 20, 30])

## 3-1-2) 2차원 배열

In [120]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [121]:
a2[0, 2]

30

In [123]:
# 기존 원소 변경

a2[0, 2] = 50
a2

array([[10, 20, 50],
       [40, 50, 60],
       [70, 80, 90]])

In [124]:
# 행 전체

a2[0] 

array([10, 20, 50])

In [126]:
# 행 전체 원소값 변경

a2[0] = np.array([44, 55, 66])
a2

array([[44, 55, 66],
       [40, 50, 60],
       [70, 80, 90]])

In [127]:
# 여러 원소 선택해서 가져오기
# a[ [행 위치1, 행 위치2, ..], [열 위치1, 열 위치2, ..] ] => [(행1,열1), (행2, 열2), ...]

a2[[0],[0, 1]] # 0행 0열, 1열

array([44, 55])

In [129]:
a2[[0, 2], [0, 1]] # 0행 0열 , 2행 1열

array([44, 80])

In [131]:
# 조건 지정
a = np.arange(1, 7)
a[a > 3]

array([4, 5, 6])

In [133]:
a[(a % 2) == 0] # 짝수

array([2, 4, 6])

## 3-2) 슬라이싱

In [134]:
b1 = np.arange(0, 60, 10)
b1

array([ 0, 10, 20, 30, 40, 50])

In [136]:
b1[1:4]

array([10, 20, 30])

In [138]:
b1[:4]

array([ 0, 10, 20, 30])

In [139]:
b1[1:]

array([10, 20, 30, 40, 50])

In [140]:
# 원소값 변경

b1[1:4] = np.array([24, 34, 54])
b1

array([ 0, 24, 34, 54, 40, 50])

In [141]:
b2 =np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [143]:
b2[0:2, 0:]

array([[10, 20, 30],
       [40, 50, 60]])

In [144]:
# 행 지정

b2[2][0:2]

array([70, 80])

In [145]:
# 원소 값 변경
b2[0:2, 0:]  = np.array([[1, 2, 3],
                        [4, 5, 6]])
b2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [70, 80, 90]])